'use strict';
angular.module('app',
	[
		'ngAnimate',
		'ngRoute',
		'ngSanitize',
		'ngTouch',
		'angular-inview',
		'matchMedia',
		'ipCookie',
		'restangular',
		'angulartics',
		'angulartics.google.analytics',
		'seo',
		'ui.bootstrap',
		'rgkevin.datetimeRangePicker',
		'naif.base64',
		'counter',
		'satellizer'
	]
);
